services:
  - type: web
    name: currency-savings-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python currency_savings_bot.py
    plan: free
    autoDeploy: true
buildCommand: |
  chmod +x force-reinstall.sh
  ./force-reinstall.sh
