services:
  - type: web
    name: currency-savings-bot
    env: python
    buildCommand: |
      chmod +x force-reinstall.sh
      ./force-reinstall.sh
    startCommand: python currency_savings_bot.py
    plan: free
